[tool.uv.workspace]
members = [
    "packages/pylutron-integration",
    "packages/pylutron-integration-cli",
]

[tool.uv.sources]
pylutron-integration = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
