[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pylutron-integration-cli"
version = "0.0.0"
description = "Command-line tools for pylutron-integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pylutron-integration==0.0.0",
]

[project.scripts]
lutron_monitor = "pylutron_integration_cli.monitor:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pylutron_integration_cli"]
