[project]
name = "lutron-integration-tools"
version = "0.0.0"
description = "Command-line tools for pylutron-integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lutron-integration==0.0.0",
]

[project.scripts]
lutron_monitor = "lutron_integration_tools.monitor:main"

[build-system]
requires = ["uv_build >= 0.9.8, <0.10.0"]
build-backend = "uv_build"